name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
  
    - name: Build main
      run: cd JaebeMusicStudio3.Front; dotnet publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Zip
        path: JaebeMusicStudio3.Front\bin\Release\net9.0-windows\publish

    - name: Generate ZIP
      uses: byteever/action-build-zip@master
      with:
        filename: 'Files.zip'

    - name: Test
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: .

    - name: Build installer
      run: cd JaebeMusicStudio3.Installer; dotnet publish
