name: .NET Core Desktop

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
    
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Build main
        run: cd JaebeMusicStudio3.Front; dotnet publish

      - name: Generate ZIP
        run: rm JaebeMusicStudio3.Installer\Files.zip; Compress-Archive JaebeMusicStudio3.Front\bin\Release\net9.0-windows\publish\* JaebeMusicStudio3.Installer\Files.zip

      - name: Build installer
        run: cd JaebeMusicStudio3.Installer; dotnet publish -p:PublishSingleFile=true -p:PublishReadyToRun=true -c Release -r win-x64 --self-contained true
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload installer exe to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/JaebeMusicStudio3.Installer.exe
          asset_name: JaebeMusicStudio3.Installer.exe
          asset_content_type: application/octet-stream
